server.port=8082
spring.application.name=cart-service

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=microservices_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=swetha
spring.datasource.password=swetha
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true